version: '3'
services:
  wallet-backend:
    build:
      context: ./docker/
      dockerfile: ./Dockerfile
    image: wallet/php-8.3
    container_name: wallet-app
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
